<?xml version="1.0" encoding="utf-8"?><Database Name="Project" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=naziproject.database.windows.net;Initial Catalog=Project;Persist Security Info=True;User ID=Nazi" SettingsObjectName="WpfApp1.Properties.Settings" SettingsPropertyName="ProjectConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PapersTable" Member="PapersTables">
    <Type Name="PapersTable">
      <Column Name="Title" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Authors" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Contents" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Link" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>